// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aeexdylocrcncuyxzrbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlZXhkeWxvY3JjbmN1eXh6cmJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3OTgzNzgsImV4cCI6MjA4NjM3NDM3OH0.f_vfFQcf-XHFdFQWPsMyfKYm66Rtq90Vm6zUiwnH3JM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});